# Generated by Django 2.0.6 on 2018-07-02 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0002_emp'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='comment_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='read_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='up_count',
            field=models.IntegerField(default=0),
        ),
    ]
